// CREATE HTTP WEB PAGE ON WHICH HOME PAGE DISPLAY WELCOME TO HOME PAGE IN BLUE COLOR AND FOT THE SIZE 32PX LOGIN PAGE SOURCE 1 HTML FILE FROM YOUR DIRECTORY.GALLRY PAGE REFLECTS 1 IMG FROM YOUR DIRECTORY AND ANY REQUEST SHOWS PAGE NOT FOUND MSG.

var http=require("http")
var url=require('url')
var fs =require("fs")

