var pm=require("path")
path =pm.dirname("C:\Users\LJENG\Downloads\FSD_A3\js11.js")
console.log(path)
path1=pm.basename("C:\Users\LJENG\Downloads\FSD_A3")
console.log(path1)
path2 =pm.extname("C:\Users\LJENG\Downloads\FSD_A3\js11.js")
console.log(path2)
path3=pm.parse("C:\Users\LJENG\Downloads\FSD_A3")
console.log(path3)
